ALTER TABLE profile ADD COLUMN translation_source_version BIGINT NOT NULL DEFAULT 1;
ALTER TABLE social_links ADD COLUMN translation_source_version BIGINT NOT NULL DEFAULT 1;
ALTER TABLE experiences ADD COLUMN translation_source_version BIGINT NOT NULL DEFAULT 1;
ALTER TABLE projects ADD COLUMN translation_source_version BIGINT NOT NULL DEFAULT 1;
ALTER TABLE writings ADD COLUMN translation_source_version BIGINT NOT NULL DEFAULT 1;
ALTER TABLE talks ADD COLUMN translation_source_version BIGINT NOT NULL DEFAULT 1;

CREATE TABLE profile_translations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  profile_id BIGINT NOT NULL REFERENCES profile(id) ON DELETE CASCADE,
  locale TEXT NOT NULL CHECK (locale IN ('en', 'ja')),
  translation_status TEXT NOT NULL CHECK (translation_status IN ('ai_draft', 'reviewed')),
  source_version BIGINT NOT NULL,
  name TEXT NOT NULL,
  headline TEXT NOT NULL,
  summary TEXT NOT NULL,
  bio TEXT NOT NULL,
  seo_title TEXT,
  seo_description TEXT,
  translated_at TIMESTAMPTZ,
  updated_at TIMESTAMPTZ NOT NULL,
  UNIQUE (profile_id, locale)
);

CREATE TABLE social_link_translations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  social_link_id BIGINT NOT NULL REFERENCES social_links(id) ON DELETE CASCADE,
  locale TEXT NOT NULL CHECK (locale IN ('en', 'ja')),
  translation_status TEXT NOT NULL CHECK (translation_status IN ('ai_draft', 'reviewed')),
  source_version BIGINT NOT NULL,
  label TEXT NOT NULL,
  translated_at TIMESTAMPTZ,
  updated_at TIMESTAMPTZ NOT NULL,
  UNIQUE (social_link_id, locale)
);

CREATE TABLE experience_translations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  experience_id BIGINT NOT NULL REFERENCES experiences(id) ON DELETE CASCADE,
  locale TEXT NOT NULL CHECK (locale IN ('en', 'ja')),
  translation_status TEXT NOT NULL CHECK (translation_status IN ('ai_draft', 'reviewed')),
  source_version BIGINT NOT NULL,
  period TEXT NOT NULL,
  title TEXT NOT NULL,
  organization TEXT NOT NULL,
  description TEXT NOT NULL,
  translated_at TIMESTAMPTZ,
  updated_at TIMESTAMPTZ NOT NULL,
  UNIQUE (experience_id, locale)
);

CREATE TABLE project_translations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id BIGINT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  locale TEXT NOT NULL CHECK (locale IN ('en', 'ja')),
  translation_status TEXT NOT NULL CHECK (translation_status IN ('ai_draft', 'reviewed')),
  source_version BIGINT NOT NULL,
  title TEXT NOT NULL,
  slug TEXT NOT NULL,
  summary TEXT NOT NULL,
  content_md TEXT NOT NULL,
  seo_title TEXT,
  seo_description TEXT,
  translated_at TIMESTAMPTZ,
  updated_at TIMESTAMPTZ NOT NULL,
  UNIQUE (project_id, locale),
  UNIQUE (locale, slug)
);

CREATE TABLE writing_translations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  writing_id BIGINT NOT NULL REFERENCES writings(id) ON DELETE CASCADE,
  locale TEXT NOT NULL CHECK (locale IN ('en', 'ja')),
  translation_status TEXT NOT NULL CHECK (translation_status IN ('ai_draft', 'reviewed')),
  source_version BIGINT NOT NULL,
  title TEXT NOT NULL,
  slug TEXT NOT NULL,
  excerpt TEXT NOT NULL,
  content_md TEXT NOT NULL,
  seo_title TEXT,
  seo_description TEXT,
  translated_at TIMESTAMPTZ,
  updated_at TIMESTAMPTZ NOT NULL,
  UNIQUE (writing_id, locale),
  UNIQUE (locale, slug)
);

CREATE TABLE talk_translations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  talk_id BIGINT NOT NULL REFERENCES talks(id) ON DELETE CASCADE,
  locale TEXT NOT NULL CHECK (locale IN ('en', 'ja')),
  translation_status TEXT NOT NULL CHECK (translation_status IN ('ai_draft', 'reviewed')),
  source_version BIGINT NOT NULL,
  title TEXT NOT NULL,
  slug TEXT NOT NULL,
  summary TEXT NOT NULL,
  event_name TEXT NOT NULL,
  seo_title TEXT,
  seo_description TEXT,
  translated_at TIMESTAMPTZ,
  updated_at TIMESTAMPTZ NOT NULL,
  UNIQUE (talk_id, locale),
  UNIQUE (locale, slug)
);
