ALTER TABLE media_assets
  ADD COLUMN storage_backend TEXT NOT NULL DEFAULT 'local' CHECK (storage_backend IN ('local', 'minio')),
  ADD COLUMN lifecycle_state TEXT NOT NULL DEFAULT 'active' CHECK (lifecycle_state IN ('active', 'pending_import')),
  ADD COLUMN media_kind TEXT NOT NULL DEFAULT 'image' CHECK (media_kind IN ('image', 'video', 'audio'));

ALTER TABLE media_assets
  ALTER COLUMN width DROP NOT NULL,
  ALTER COLUMN height DROP NOT NULL;

DO 'DECLARE
BEGIN
  IF EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conrelid = ''media_assets''::regclass
      AND contype = ''c''
      AND conname = ''media_assets_width_check''
      AND pg_get_constraintdef(oid) = ''CHECK ((width > 0))''
  ) THEN
    EXECUTE ''ALTER TABLE media_assets DROP CONSTRAINT media_assets_width_check'';
  END IF;

  IF EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conrelid = ''media_assets''::regclass
      AND contype = ''c''
      AND conname = ''media_assets_height_check''
      AND pg_get_constraintdef(oid) = ''CHECK ((height > 0))''
  ) THEN
    EXECUTE ''ALTER TABLE media_assets DROP CONSTRAINT media_assets_height_check'';
  END IF;
END';

ALTER TABLE media_assets
  ADD CONSTRAINT media_assets_kind_dimensions_check CHECK (
    (media_kind = 'image' AND width IS NOT NULL AND width > 0 AND height IS NOT NULL AND height > 0)
    OR
    (media_kind IN ('audio', 'video') AND width IS NULL AND height IS NULL)
  );

CREATE TABLE writing_import_sessions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  token_hash TEXT NOT NULL UNIQUE,
  admin_session_id BIGINT NOT NULL,
  mode TEXT NOT NULL CHECK (mode IN ('create', 'overwrite')),
  target_writing_id BIGINT REFERENCES writings(id) ON DELETE SET NULL,
  target_writing_etag TEXT,
  source_file_name TEXT NOT NULL,
  source_checksum_sha256 TEXT NOT NULL,
  front_matter JSONB NOT NULL DEFAULT '{}'::jsonb,
  ignored_front_matter_keys JSONB NOT NULL DEFAULT '[]'::jsonb,
  original_markdown TEXT NOT NULL,
  rewritten_markdown TEXT NOT NULL,
  parsed_payload JSONB NOT NULL DEFAULT '{}'::jsonb,
  status TEXT NOT NULL CHECK (status IN ('preview_ready', 'committed', 'expired', 'failed')),
  expires_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE writing_import_session_assets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id BIGINT NOT NULL REFERENCES writing_import_sessions(id) ON DELETE CASCADE,
  media_asset_id BIGINT NOT NULL REFERENCES media_assets(id) ON DELETE CASCADE,
  original_relative_path TEXT NOT NULL,
  normalized_source_path TEXT NOT NULL,
  replacement_ref TEXT NOT NULL,
  status TEXT NOT NULL CHECK (status IN ('prepared', 'failed', 'activated', 'cleaned')),
  error_message TEXT,
  created_at TIMESTAMPTZ NOT NULL
);

CREATE INDEX writing_import_sessions_expires_at_idx ON writing_import_sessions (expires_at);
CREATE INDEX writing_import_sessions_admin_session_id_idx ON writing_import_sessions (admin_session_id);
CREATE INDEX writing_import_session_assets_session_id_idx ON writing_import_session_assets (session_id);
CREATE INDEX writing_import_session_assets_media_asset_id_idx ON writing_import_session_assets (media_asset_id);
