CREATE TABLE experience_tech (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  experience_id BIGINT NOT NULL REFERENCES experiences(id) ON DELETE CASCADE,
  tech_id BIGINT NOT NULL REFERENCES techs(id) ON DELETE RESTRICT,
  sort_order INTEGER NOT NULL DEFAULT 0,
  UNIQUE (experience_id, tech_id)
);

CREATE INDEX idx_experience_tech_tech_id ON experience_tech (tech_id);
