CREATE TABLE writing_likes (
  writing_id BIGINT PRIMARY KEY REFERENCES writings(id) ON DELETE CASCADE,
  like_count INTEGER NOT NULL DEFAULT 0 CHECK (like_count >= 0),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE writing_comments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  writing_id BIGINT NOT NULL REFERENCES writings(id) ON DELETE CASCADE,
  author_name TEXT NOT NULL,
  author_email TEXT NOT NULL DEFAULT '',
  body TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'published' CHECK (status IN ('published', 'hidden')),
  created_at TIMESTAMPTZ NOT NULL
);

CREATE INDEX idx_writing_comments_public
  ON writing_comments (writing_id, status, created_at DESC);
